# Generated by Django 4.1.3 on 2023-02-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
