# Generated by Django 4.1.3 on 2023-02-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolwork', '0003_alter_student_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rf_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
