# Generated by Django 4.1.3 on 2023-02-21 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolwork', '0004_student_rf_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('jan', 'january'), ('feb', 'feb'), ('march', 'march'), ('april', 'april'), ('may', 'may'), ('june', 'june'), ('july', 'july'), ('aug', 'aug'), ('sep', 'sep'), ('oct', 'oct'), ('nov', 'nov'), ('dec', 'dec')], max_length=200)),
                ('date_of_payment', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolwork.student')),
            ],
        ),
    ]
